### ISSUE TITLE
Nested normal-flow pieces not working?

### ISSUE THREAD

**Issue by ivanreese** [cdig/piece-it-together#10]
I have [a test build](https://github.com/ivanreese/pit-issue-10) that I believe shows PIT not working as expected.

The test build has two aspects that make it different from most other recent examples that I've seen: pieces nested deeply inside DOM elements, and pieces in normal flow. I'd like to know if either or both are unsupported. According to the docs (which are spartan and outdated, natch), both nesting and normal-flow should be supported. If they are both supported, then something (either in my build, or in PIT) is broken, and I'd like to know what. I also have reasonable confidence that my test build is correct — but then again, we all have our bad days.

If you comment out [this line](https://github.com/cdig/piece-it-together/blob/master/dist/core/pieces-setup.coffee#L9), you will see that the original pieces are positioned correctly at all times. The cloned pieces also look correct when in the panel, and when being dragged. They also respond correctly to being dropped in the correct drop zones. But following that, they animate to wildly erroneous final positions.

The test build is not responsive, so please do not take the weird layout at small sizes as a sign of incorrect implementation. I stripped out the media queries in order to supply a minimal test build.

**Comment by theseanzo** [comment]
Looking at this now.

**Comment by theseanzo** [comment]
Nesting is a pain in the ass. I've been trying to make changes and, unfortunately, there are going to be a lot of circumstances in which nesting will present issues unless we make strict guidelines about what can or cannot be done with piece it together that involve copious amount of explanation (in fact, right now, I'm still not fully sure what they all are).

First, what happens currently is that elements are cloned and their draggable element is then placed in relation to the cd-map that contains the activity. This presents tremendous issues for nesting, as the width and height of nested elements (like in this case), may be affected by their parents and these changes will not be represented in the cloned element.

What I've tried doing is that, instead of cloning and placing in relation to the cd-map, these elements are placed within relation to the immediate parent of the element they are cloning. This can work, but again we are presented with a host of potential issues:
*For one thing, these cloned items have to be absolutely positioned so as to not affect the flow of the original element, or the parent which may have a size based on its internal elements (like in this example). 
*These items now have a z-index on dragging that is in relation to their first relative parent. The Z-index will not, unfortunately, be in relation to all other elements on screen. Therefore, we will inevitably run into z-index problems. Check out [http://philipwalton.com/articles/what-no-one-told-you-about-z-index/](a discussion of this).

So, after a couple of hours...No. I really prefer if we don't have nesting.

**Comment by ivanreese** [comment]
Refresh my memory: Why aren't we just applying transforms to the original piece?

**Comment by ivanreese** [comment]
This issue is stale, and PiT deserves a redo in SVGA.
